name: Playwright Tests
on:
  push:
    tags:
      - v0.*
  schedule:
    # M-F 0AM UTC+9
    - cron: '0 15 * * 1-5'

jobs:
  test-chrome:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.COMMIT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install
      - run: yarn playwright install --with-deps
      - run: yarn playwright test --project="Mobile Chrome" --project="Mobile Chrome landscape"
      - run: yarn playwright test -u
        if: ${{ failure() }}
      - run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git config --global push.autoSetupRemote true
          git switch -c "snapshots/chrome/`date '+%y/%m/%d'`"
          git add .
          git commit -am "chore: update image snapshots by github actions"
          git push
          gh pr create --fill
        if: ${{ failure() }}
      - uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      # - uses: slackapi/slack-github-action@v1.24.0
      #   if: ${{ success() }}
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secret.SLACK_WEBHOOK_URL }}
      #   with:
      #     payload: |
      #       {
      #         "type": "success",
      #         "repo": ${{ github.repository }}
      #         "ref": ${{ github.ref }}
      #         "link": ${{ github.server.url }}
      #       }
      # - uses: slackapi/slack-github-action@v1.24.0
      #   if: ${{ failure() }}
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secret.SLACK_WEBHOOK_URL }}
      #   with:
      #     payload: |
      #       {
      #         "type": "success",
      #         "repo": ${{ github.repository }}
      #         "ref": ${{ github.ref }}
      #         "link": ${{ github.server.url }}
      #       }
