name: Playwright Tests
on:
  push:
    tags:
      - v0.*
  # schedule:
  #   # M-F 0AM UTC+9
  #   - cron: '*/5 * * * *'

jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-13 
    steps:
<<<<<<< Updated upstream
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.COMMIT_TOKEN }}  
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - run: yarn
    - run: yarn playwright install --with-deps
    - run: yarn playwright test -u
    - run: |
        git config --global user.email "github-action@github.com"
        git config --global user.name "github-actions"
        git config --global push.autoSetupRemote true
        git switch -c "snapshots/`date '+%d/%m/%y'`"
        git add .
        git commit -am "chore: update image snapshots by github actions"
        git push
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
=======
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.COMMIT_TOKEN }}  
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install
      - run: yarn playwright install --with-deps
      - run: yarn playwright test
      - uses: slackapi/slack-github-action@v1.24.0
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secret.SLACK_WEBHOOK_URL }}
      - uses: slackapi/slack-github-action@v1.24.0
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secret.SLACK_WEBHOOK_URL }}
      - run: |
          git config --global push.autoSetupRemote true
          git switch -c "snapshots/chrome/`date '+%d/%m/%y'`"
          git add .
          git commit -am "chore: update image snapshots by github actions"
          git push
          gh pr create
        if: ${{ failure() }}
      - uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
>>>>>>> Stashed changes
