name: Playwright Tests
on:
  push:
    tags:
      - v0.*
  schedule:
    # M-F 0AM UTC+9
    - cron: '*/5 * * * *'

jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-13 
    steps:
    - uses: actions/checkout@v4
      with: 
        token: ${{ secrets.COMMIT_TOKEN }}
        
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test -u
    - run: |
        git add .
        git config --global user.email "github-action@github.com"
        git config --global user.name "github-actions"
        git commit -am "chore: update scrennshots by github actions"
        git push origin main
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
